apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    group: test-pod
spec:
  containers:
    - image: k8s.gcr.io/pause:3.1
      imagePullPolicy: IfNotPresent
      name: {{.Name}}
      volumeMounts:
      {{range $volumeIndex, $vol := Seq .PVCsPerPod}}
        - mountPath: /pvc-{{$volumeIndex}}
          name: pod-pvc-{{$volumeIndex}}
      {{end}}
  volumes:
    {{$PVCInitialIndex := MultiplyInt .Index .PVCsPerPod}}
    {{range $volumeIndex, $vol := Seq .PVCsPerPod}}
    - name: pod-pvc-{{$volumeIndex}}
      persistentVolumeClaim:
        claimName: pvc-{{AddInt $PVCInitialIndex $volumeIndex}}
        readOnly: false
    {{end}}
  # Add not-ready/unreachable tolerations for 15 minutes so that node
  # failure doesn't trigger pod deletion.
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 900
    - key: "node.kubernetes.io/unreachable"
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 900