kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Name}}
  labels:
    group: volume-scale-tests
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.PVCSize}}
  persistentVolumeReclaimPolicy: Delete
  volumeBindingMode: Immediate